### ISSUE TITLE
Not working on ruby 1.9.3

### ISSUE THREAD

**Issue by kamilski81** [chetan/yahoo_sports#1]
@chetan - thank you for the great gem, i'm just making sure i'm not losing my mind, but is this gem only meant for ruby 1.8.7? You have any plans porting to ruby 1.9?

**Comment by chetan** [comment]
The version of scrapi I'm using currently (1.2.0) only supports ruby 1.8. I'd need to switch to scrapi 2 which only supports 1.9. The best option would probably be to release it as a separate yahoo_sports19 gem to maintain compat with both versions.

**Comment by chetan** [comment]
I just pushed the yahoo_sports19 gem. Source is available in the ruby19 branch.

**Comment by kamilski81** [comment]
Thanks @chetan
