### ISSUE TITLE
Is this project still active or functional?

### ISSUE THREAD

**Issue by SpencerCornelia** [chetan/yahoo_sports#2]

**Comment by chetan** [comment]
There are a set of unit tests which should tell you whether or not it's currently functional. Unfortunately it does operate by scraping yahoo sports, so it does break quite often. I have not tested it in some time. That said, it's usually pretty easy to fix and you're welcome to take a look.

**Comment by chetan** [comment]
Also note that I don't really use this anymore, so it's not really active..
